// see CUSTOM_LEVEL_TOKENS in default_levels.c
pub const TILES: [(&'static str, char); 22] = [
    ("water top", '~'),
    ("water", '`'),
    ("ladder", 'L'),
    ("wall top", '='),
    ("wall", '*'),
    ("ground top", '-'),
    ("grass", 'g'),
    ("ground", '_'),
    ("spider", 's'),
    ("coin", 'O'),
    ("door", 'D'),
    ("player", 'P'),
    ("sprinting spider", 'S'),
    ("ghost", 'G'),
    ("extra life", 'E'),
    ("platform", 'p'),
    ("spring", 'X'),
    ("skeleton", 'k'),
    ("rust wall top", '^'),
    ("rust wall", '#'),
    ("bat", 'b'),
    ("none", ' '),
];
